### ISSUE TITLE
[BUG] Oracle GPG Key has expired

### ISSUE THREAD

**Issue by blalop** [idealista/mysql_role#100]
### Description

Oracle GPG key has expired.

### Steps to Reproduce

Just run the role, expect this output:

```
TASK [mysql_role : MySQL | Add Oracle repo GPG key] ****************************
fatal: [mysql]: FAILED! => {"after": ["B7C5D7D6350947F8", "6ED0E7B82643E131", "254CF3B5AEC0A8F0", "BDE6D2B9216EC7A8", "F8D2585B8783D481", "73A4F27B8DD47936", "0E98404D386FA1D9", "A48449044AAD5C5D", "54404762BBB6E853", "605C66F00D6C9793", "DC30D7C23CBBABEE", "648ACFD622F3D138", "4DFAB270CAA96DFA", "112695A0E562B32A", "DCC9EFBF77E11517"], "before": ["B7C5D7D6350947F8", "6ED0E7B82643E131", "254CF3B5AEC0A8F0", "BDE6D2B9216EC7A8", "F8D2585B8783D481", "73A4F27B8DD47936", "0E98404D386FA1D9", "A48449044AAD5C5D", "54404762BBB6E853", "605C66F00D6C9793", "DC30D7C23CBBABEE", "648ACFD622F3D138", "4DFAB270CAA96DFA", "112695A0E562B32A", "DCC9EFBF77E11517"], "changed": true, "fp": "467B942D3A79BD29", "id": "467B942D3A79BD29", "key_id": "467B942D3A79BD29", "msg": "apt-key did not return an error, but failed to add the key (check that the id is correct and *not* a subkey)", "short_id": "3A79BD29"}
 ```

**Expected behavior:**

Task ending successfully.

**Actual behavior:**

See steps to reproduce.

**Reproduces how often:** 

Always.

### Environment

N/A.

### Additional Information

The key we've been using has expired: https://keyserver.ubuntu.com/pks/lookup?op=vindex&search=0x467b942d3a79bd29
New key can be found at: https://keyserver.ubuntu.com/pks/lookup?search=bca43417c3b485dd128ec6d4b7b3b788a8d3785c&fingerprint=on&op=index 

It should be enough updating the key in the role default vars.

**Comment by freddong** [comment]
workaround:

set a variable

mysql_oracle_gpg_key: bca43417c3b485dd128ec6d4b7b3b788a8d3785c

**Comment by ablancolop** [comment]
Released https://github.com/idealista/mysql_role/releases/tag/4.5.5
