### ISSUE TITLE
Install MySQL from sources

### ISSUE THREAD

**Issue by jnogol** [idealista/mysql_role#47]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

As in most idealista's Ansible roles, it would be nice to install MySQL from sources instead of packages, making it easier to control the installation.

**Comment by frantsao** [comment]
Because the idiosincrasy of MySQL and MariaDB projects, it won't provide improvements and maybe it cause some headaches. So, at this time we won't tackle this issue.
