### ISSUE TITLE
[FEATURE] Role reshaping

### ISSUE THREAD

**Issue by blalop** [idealista/mysql_role#70]
### Description

Lately we've been making some changes to our roles and this role lags behind the rest of the roles in some aspects:

* There is no .gitattributes file: https://github.com/idealista/jira_role/blob/master/.gitattributes
* There is no travis email notification config: https://github.com/idealista/jira_role/blob/master/.travis.yml#L20-L25
* Some versions in the Pipfile could be updated, at least the patch version (be aware to not break CI): https://github.com/idealista/jira_role/blob/master/Pipfile
* Add ansible-lint as dependency in the Pipfile and its config: https://github.com/idealista/jira_role/blob/master/.ansible-lint. Include ansible-lint in molecule linting stage: https://github.com/idealista/jira_role/blob/master/molecule/default/molecule.yml#L8
* Some warnings may arise because of the introduction of ansible-lint. It could be positive to fix them.
 
### Why is this needed?

So the role is updated along all the roles

### Additional Information

N/A

**Comment by vicsufer** [comment]
Also `.github` directory and its corresponding files should be added:  https://github.com/idealista/cookiecutter-ansible-role/tree/develop/%7B%7Bcookiecutter.app_name%7D%7D_role/.github
