### ISSUE TITLE
[FEATURE] Upgrading to Ansible 2.10 and beyond

### ISSUE THREAD

**Issue by blalop** [idealista/mysql_role#73]
### Description
Starting with ansible==2.10.0, the following error started to appear in the idempotence stage when running the mysql scenario with `MOLECULE_DISTRO=debian:buster-slim`:

```
TASK [mysql_role : MySQL | Ensure MySQL users are present] *********************
failed: [mysql] (item={'name': 'testing', 'password': 'testing', 'priv': ['test01.*:ALL']}) => {"ansible_loop_var": "item", "changed": false, "item": {"name": "testing", "password": "testing", "priv": ["test01.*:ALL"]}, "msg": "The PyMySQL (Python 2.7 and Python 3.X) or MySQL-python (Python 2.X) module is required."}
```

Further investigation is required. This could be easily fixed adding `python3-pymysql` to `mysql_required_libs` under `vars/mysql.yml`, but I don't think this is the best approach as it adds another dependency.

### Additional Information

Can be reproduced upgrading to ansible >= 2.10.0 and running `MOLECULE_DISTRO=debian:buster-slim pipenv run molecule test -s mysql`

Module documentation: https://docs.ansible.com/ansible/latest/collections/community/mysql/mysql_user_module.html

**Comment by frantsao** [comment]
Fixed in #80
